### PR TITLE
feat: hide home carousel 隐藏首页轮播图

### PR DESCRIPTION
**Pull request by Liumingxun**
About this PR:
- Add switch for hide carousel
- Fix type error
  In [this code](https://github.com/the1812/Bilibili-Evolved/blob/fc4fe13a7a086333bf2cd77dea535c60eeb6a49f/registry/lib/components/style/simplify/home/index.ts#L73-L76) (generatedOptions/categoryElements) that's value may be `null`, which causes the `categoryElements.map()` to throw a "TypeError: Cannot read properties of null (reading 'map')" error.

Before:
image

After:
image

### CODE REVIEW

**Comment by the1812** [comment]
编译产物不需要提交哦 (registry/dist/components/style/simplify/home.js)

**Comment by Liumingxun** [comment]
@the1812 已经重置到未修改状态了😄

**Comment by MJSummer** [comment]
现在没有简化首页了qwq，轮播图咋隐藏捏

**Comment by the1812** [comment]
之前的简化首页可以用链接装: https://raw.githubusercontent.com/the1812/Bilibili-Evolved/923382fa4e7a7244ccf516605af3914ad36a88dd/registry/dist/components/style/simplify/home.js

**Comment by MJSummer** [comment]
旧简化首页的活动/热门视频（轮播图）功能已失效。
在2.9.5更新日志#5024中，获悉应使用 [BewlyBewly](https://github.com/BewlyBewly/BewlyBewly) 替代.

**Pull request merged**
